-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."JobSeekers"
(
    "UserId" integer NOT NULL,
    "FirstName" character varying NOT NULL,
    "LastName" character varying NOT NULL,
    "NationalityId" character varying NOT NULL,
    "BirthDate" date NOT NULL,
    "Verify" boolean NOT NULL,
    "VerifyId" integer NOT NULL
);

CREATE TABLE public."Users"
(
    "UserId" integer NOT NULL,
    "Email" character varying NOT NULL,
    "Password" character varying NOT NULL,
    PRIMARY KEY ("UserId")
);

CREATE TABLE public."SytemUsers"
(
    "UserId" integer NOT NULL,
    "FirstName" character varying NOT NULL,
    "LastName" character varying NOT NULL,
    "Role" character varying NOT NULL
);

CREATE TABLE public."Companies"
(
    "UserId" integer NOT NULL,
    "CompanyName" character varying NOT NULL,
    "Website" character varying NOT NULL,
    "Phone" integer NOT NULL,
    "Verify" boolean NOT NULL,
    "VerifyId" integer NOT NULL
);

CREATE TABLE public."VerifyTypes"
(
    "VerifyId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "VerfiyType" character varying NOT NULL,
    PRIMARY KEY ("VerifyId")
);

CREATE TABLE public."Positions"
(
    "PositionId" integer NOT NULL,
    "PositionName" character varying NOT NULL,
    PRIMARY KEY ("PositionId")
);

ALTER TABLE public."JobSeekers"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("UserId")
    NOT VALID;


ALTER TABLE public."SytemUsers"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("UserId")
    NOT VALID;


ALTER TABLE public."Companies"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("UserId")
    NOT VALID;


ALTER TABLE public."VerifyTypes"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("UserId")
    NOT VALID;


ALTER TABLE public."JobSeekers"
    ADD FOREIGN KEY ("VerifyId")
    REFERENCES public."VerifyTypes" ("VerifyId")
    NOT VALID;


ALTER TABLE public."Companies"
    ADD FOREIGN KEY ("VerifyId")
    REFERENCES public."VerifyTypes" ("VerifyId")
    NOT VALID;

END;