-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.companies
(
    company_name character varying(255),
    verify boolean,
    website character varying(255),
    user_id integer NOT NULL,
    phone character varying(255),
    PRIMARY KEY (user_id)
);

CREATE TABLE public.job_seekers
(
    birth_date timestamp without time zone,
    first_name character varying(255),
    last_name character varying(255),
    nationality_id character varying(255),
    verify boolean,
    user_id integer NOT NULL,
    verify_id integer,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.positions
(
    position_id integer NOT NULL,
    position_name character varying NOT NULL,
    PRIMARY KEY (position_id)
);

CREATE TABLE public.sytem_users
(
    user_id integer NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    role character varying NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.users
(
    user_id integer NOT NULL,
    email character varying(255),
    enter_password_again character varying(255),
    password character varying(255),
    PRIMARY KEY (user_id)
);

CREATE TABLE public.verify_types
(
    verify_type character varying(255),
    user_id integer NOT NULL,
    PRIMARY KEY (user_id)
);

ALTER TABLE public.companies
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.job_seekers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.verify_types
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;

END;
